import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, LegalSection } from "@/components/legal-page";

export const metadata: Metadata = { title: "Privacy Policy", description: "How Flowvia Health handles information, SMS consent, mobile number privacy, and data security.", alternates: { canonical: "/privacy" }, openGraph: { title: "Flowvia Health Privacy Policy", url: "/privacy" } };

export default function PrivacyPage() {
  return <LegalPage title="Privacy Policy" effectiveDate="June 24, 2026" intro="This policy explains the information Flowvia Health may collect through this public website and how we approach privacy, SMS consent, and data security.">
    <LegalSection title="Information We Collect"><p>We may collect information you voluntarily provide through website forms, such as your name, email address, mobile phone number, message, and SMS consent selection. We may also collect limited technical information such as browser type, device type, and website usage data.</p><p>This public website is not intended to collect protected health information, medical records, diagnoses, treatment details, or emergency requests.</p></LegalSection>
    <LegalSection title="How We Use Information"><p>We use information to respond to inquiries, operate and improve our services, communicate about Flowvia Health, maintain security, and support the purposes described when information is collected.</p></LegalSection>
    <LegalSection title="SMS Communications"><p>SMS consent is used only to send appointment reminders, scheduling updates, care coordination messages, patient communication, and related service notifications.</p><p>Message frequency varies. Message and data rates may apply. Reply STOP to opt out or HELP for assistance.</p></LegalSection>
    <LegalSection title="SMS Consent and Mobile Number Privacy"><p>Mobile information, SMS opt-in data, and SMS consent information will not be shared, sold, rented, or disclosed to third parties or affiliates for marketing or promotional purposes.</p><p>Consent is not a condition of receiving healthcare services. See the <Link href="/sms-consent" className="font-semibold text-blue underline">SMS Consent page</Link> for the complete opt-in disclosure.</p></LegalSection>
    <LegalSection title="No Sale or Sharing of SMS Data"><p>Flowvia Health does not sell or share mobile numbers, SMS opt-in data, or consent information with third parties or affiliates for marketing or promotional purposes. Information may be used by service providers only as necessary to deliver requested services, subject to appropriate restrictions.</p></LegalSection>
    <LegalSection title="HIPAA-Conscious Practices"><p>Flowvia Health is being designed with privacy-conscious workflows for healthcare communication. This public website is not a patient portal and should not be used to submit sensitive medical information. Future regulated services will require appropriate technical safeguards, policies, agreements, and operational controls before handling protected health information.</p></LegalSection>
    <LegalSection title="Data Security"><p>We use reasonable administrative, technical, and organizational safeguards appropriate to the information and services involved. No method of internet transmission or electronic storage is completely secure, and we cannot guarantee absolute security.</p></LegalSection>
    <LegalSection title="Contact Us"><p>Questions about this policy may be submitted through our <Link href="/contact" className="font-semibold text-blue underline">Contact page</Link>. Do not include protected health information or sensitive medical details.</p></LegalSection>
  </LegalPage>;
}
