import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, LegalSection } from "@/components/legal-page";

export const metadata: Metadata = { title: "Terms of Service", description: "Terms governing use of the Flowvia Health website and transactional healthcare SMS program operated by Onzeon Holdings LLC.", alternates: { canonical: "/terms" }, openGraph: { title: "Flowvia Health Terms of Service", url: "/terms" } };

export default function TermsPage() {
  return <LegalPage title="Terms of Service" effectiveDate="June 26, 2026" intro="These terms govern your use of the Flowvia Health public website and participation in the Flowvia Health transactional healthcare SMS program. Flowvia Health is owned, developed, and operated by Onzeon Holdings LLC.">
    <LegalSection title="Website Use"><p>You may use this website for lawful informational purposes. You may not interfere with the website, attempt unauthorized access, or use the website in a way that violates applicable law or the rights of others.</p></LegalSection>
    <LegalSection title="Product Information"><p>Flowvia Health describes a healthcare workflow, scheduling, care coordination, and transactional healthcare messaging platform. Concept previews are illustrative and do not promise that a feature is currently available or will be released in a particular form or timeframe.</p></LegalSection>
    <LegalSection title="Company Relationship"><p>Flowvia Health is a healthcare workflow, scheduling, care coordination, and transactional healthcare messaging platform owned, developed, and operated by Onzeon Holdings LLC. The public corporate website for Onzeon Holdings LLC is <a href="https://www.onzeonholdings.com" className="font-semibold text-blue underline">www.onzeonholdings.com</a>.</p></LegalSection>
    <LegalSection title="SMS Program Terms"><p>By providing your mobile number and consenting to receive SMS communications from Flowvia Health, you agree to receive transactional healthcare text messages related to appointment reminders, appointment confirmations, scheduling updates, therapist arrival notifications, care coordination, responses to scheduling questions, patient inquiries, and other healthcare service notifications.</p><p>Flowvia Health does not use this SMS program for advertising or promotional marketing.</p><p>Message frequency varies. Message and data rates may apply.</p><p>To stop receiving messages, reply STOP.</p><p>For assistance, reply HELP or contact <a href="mailto:support@flowviahealth.com" className="font-semibold text-blue underline">support@flowviahealth.com</a>.</p><p>Carriers are not liable for delayed or undelivered messages. Consent is not required as a condition of receiving healthcare services.</p><p><strong className="text-ink">No emergency use.</strong> If you are experiencing a medical emergency, call 911.</p><p>Additional privacy terms appear in our <Link href="/privacy" className="font-semibold text-blue underline">Privacy Policy</Link>, and the complete opt-in disclosure appears on our <Link href="https://flowviahealth.com/sms-consent" className="font-semibold text-blue underline">SMS Consent page at https://flowviahealth.com/sms-consent</Link>.</p></LegalSection>
    <LegalSection title="No Medical Advice"><p>This website and any general service communications do not provide medical advice, diagnosis, or treatment. Contact an appropriate licensed healthcare professional with questions about your care.</p></LegalSection>
    <LegalSection title="Intellectual Property"><p>Flowvia Health names, designs, site content, and related materials are owned by Onzeon Holdings LLC or its licensors and are protected by applicable intellectual property laws.</p></LegalSection>
    <LegalSection title="Disclaimer and Limitation"><p>The public website is provided on an “as is” and “as available” basis to the extent permitted by law. Flowvia Health does not warrant uninterrupted or error-free operation. Liability is limited to the fullest extent permitted by applicable law.</p></LegalSection>
    <LegalSection title="Changes and Contact"><p>We may update these terms from time to time by posting a revised version with a new effective date. Legal notices may be sent to <a href="mailto:legal@flowviahealth.com" className="font-semibold text-blue underline">legal@flowviahealth.com</a>. General questions may be submitted through the <Link href="/contact" className="font-semibold text-blue underline">Contact page</Link>.</p></LegalSection>
  </LegalPage>;
}
