import type { Metadata } from "next";
import { FileKey2, KeyRound, Lock, ScrollText, ShieldCheck, UserCog } from "lucide-react";

export const metadata: Metadata = { title: "HIPAA & Security", description: "Flowvia Health’s HIPAA-conscious product direction and future security concepts.", alternates: { canonical: "/hipaa" }, openGraph: { title: "Flowvia Health HIPAA & Security", url: "/hipaa" } };

const concepts = [["Role-based access","Support access based on a team member’s responsibilities.",UserCog],["Audit logging","Create a reviewable record of key activity and changes.",ScrollText],["Encrypted data handling","Protect sensitive data in transit and at rest within future secure infrastructure.",FileKey2],["Secure patient communication","Design communication channels around appropriate identity, consent, and privacy controls.",Lock],["Access controls","Apply authentication and authorization controls to protected product areas.",KeyRound],["Administrative safeguards","Pair technology with documented policies, training, risk review, and operational accountability.",ShieldCheck]] as const;

export default function HipaaPage() {
  return <>
    <section className="border-b border-line bg-ink py-20 text-white sm:py-24"><div className="container-page grid gap-10 lg:grid-cols-[1.25fr_.75fr] lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-teal">Security direction</p><h1 className="mt-5 text-4xl font-semibold tracking-[-.04em] sm:text-6xl">HIPAA & Security</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-blue-100/80">Flowvia Health is being designed with HIPAA-conscious workflows for healthcare communication and care coordination. This public website does not collect protected health information and should not be used to submit sensitive medical information.</p></div><div className="rounded-2xl border border-white/15 bg-white/5 p-6"><ShieldCheck className="text-teal" size={30}/><p className="mt-4 text-sm leading-6 text-blue-50">We do not claim that the future Flowvia Health platform is fully HIPAA compliant. Compliance depends on implemented infrastructure, policies, operating practices, vendor relationships, and appropriate business associate agreements.</p></div></div></section>
    <section className="section-space"><div className="container-page"><div className="max-w-3xl"><p className="eyebrow">Future platform concepts</p><h2 className="section-title mt-4">Safeguards designed as a system.</h2><p className="body-lg mt-5">Technical controls matter most when they are paired with clear operational responsibility.</p></div><div className="mt-14 grid gap-px overflow-hidden rounded-2xl border border-line bg-line sm:grid-cols-2 lg:grid-cols-3">{concepts.map(([title,copy,Icon])=><article key={title} className="bg-white p-7 sm:min-h-60"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-mist text-blue"><Icon size={22}/></span><h3 className="mt-8 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{copy}</p></article>)}</div></div></section>
    <section className="border-t border-line bg-mist py-16"><div className="container-page max-w-4xl"><h2 className="text-2xl font-semibold tracking-[-.025em]">Public website boundary</h2><p className="mt-4 leading-7 text-slate-600">Do not use public forms on this website to submit protected health information, medical records, clinical details, or emergency requests. Future product environments intended to handle regulated information would require safeguards and agreements appropriate to their actual use.</p></div></section>
  </>;
}
